"use client";

import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useMemo, useState } from "react";
import type { MarketplaceWorkspaceRecord } from "../../lib/marketplace-v12-workspaces";
import MarketplaceSpatialStage from "./MarketplaceSpatialStage";
import styles from "./MarketplaceWorkspaces.module.css";

const LIMIT = 8;
function plain(value: string | null) { return value ? value.replace(/[-_]/g, " ") : "Not recorded"; }
function initials(value: string) { return value.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase(); }

export default function MarketplaceBundleComposer({ anchor, records, candidates, facts, invalidReason }: { anchor: MarketplaceWorkspaceRecord | null; records: MarketplaceWorkspaceRecord[]; candidates: MarketplaceWorkspaceRecord[]; facts: { relationships: { edges: { sourceProductId: string; targetProductId: string }[]; isolatedProductIds: string[] }; compatibility: string; prerequisites: string; licenseScope: string; activation: string }; invalidReason: string | null }) {
  const router = useRouter(), pathname = usePathname(), params = useSearchParams();
  const allNodes = anchor && !records.some((record) => record.productId === anchor.productId) ? [anchor, ...records] : records;
  const [selectedId, setSelectedId] = useState<string | null>(anchor?.productId ?? records[0]?.productId ?? null);
  const selected = allNodes.find((record) => record.productId === selectedId) ?? allNodes[0] ?? null;
  const selectedIds = useMemo(() => new Set(records.map((record) => record.productId)), [records]);
  const replace = (next: MarketplaceWorkspaceRecord[], nextAnchor = anchor) => { const query = new URLSearchParams(params.toString()); if (next.length) query.set("items", next.map((record) => record.slug).sort().join(",")); else query.delete("items"); if (nextAnchor?.mission) query.set("mission", nextAnchor.slug); else query.delete("mission"); router.replace(`${pathname}${query.size ? `?${query}` : ""}`, { scroll: false }); };
  return <>
    <section className={styles.intro} aria-labelledby="composer-title"><div><p className={styles.eyebrow}>Mission and bundle composer</p><h1 id="composer-title">Build a governed selection from exact catalog evidence.</h1><p>There is no inferred compatibility, discount, bundle price, or activation path. The server validates all selected product IDs and the stage visualizes only catalog-declared relationships.</p></div><aside><span>Current selection</span><strong>{records.length} / {LIMIT} records</strong><p>{anchor?.mission ? `Mission anchor: ${anchor.name}` : "Choose an anchor with a recorded mission."}</p></aside></section>
    {invalidReason && <p className={styles.alert} role="alert">{invalidReason}</p>}
    <section className={styles.stageLayout} aria-labelledby="composer-spatial-title"><div className={styles.stageCopy}><p className={styles.eyebrow}>Composition field</p><h2 id="composer-spatial-title">One spatial system, controlled by server facts.</h2><p>{selected ? `${selected.name} is selected. ${facts.relationships.edges.length} declared relationship edge${facts.relationships.edges.length === 1 ? "" : "s"} exist inside the current composition.` : "Select a mission anchor or catalog record to begin a factual composition."}</p>{selected && <Link className={styles.secondaryAction} href={`/ai-marketplace/${encodeURIComponent(selected.slug)}`}>Inspect selected record</Link>}</div><MarketplaceSpatialStage label="Marketplace mission and bundle composer" nodes={allNodes} selectedId={selected?.productId} onSelect={(node) => setSelectedId(node.productId)} emptyMessage="No mission or catalog records are selected. The composer does not create a synthetic bundle." /></section>
    <section className={styles.selectorSection} aria-labelledby="mission-anchor"><div><p className={styles.eyebrow}>Mission anchor</p><h2 id="mission-anchor">Select a catalog record with a factual mission.</h2><p>These are real catalog records. Selecting an anchor stores its stable slug in the URL; it does not make a commercial recommendation.</p></div><div className={styles.selectorOrbit}>{candidates.filter((candidate) => candidate.mission).map((candidate, index) => { const active = anchor?.productId === candidate.productId; return <button type="button" key={candidate.productId} className={active ? styles.selected : undefined} aria-pressed={active} onClick={() => replace(records, candidate)}><i style={{ "--orbit": `${index * 31}deg` } as React.CSSProperties} /><span>{candidate.family}</span><strong>{candidate.name}</strong><small>{active ? "Current mission anchor" : candidate.mission}</small></button>; })}</div></section>
    <section className={styles.selectorSection} aria-labelledby="bundle-selection"><div><p className={styles.eyebrow}>Catalog selection</p><h2 id="bundle-selection">Add records without claiming an unverified package.</h2><p>Records retain their own server-provided terms. Combined checkout is unavailable unless a future server-governed bundle record and payment controls exist.</p></div><div className={styles.selectorOrbit}>{candidates.map((candidate, index) => { const included = selectedIds.has(candidate.productId), disabled = !included && records.length >= LIMIT; return <button type="button" key={candidate.productId} className={included ? styles.selected : undefined} aria-pressed={included} disabled={disabled} onClick={() => replace(included ? records.filter((record) => record.productId !== candidate.productId) : [...records, candidate])}><i style={{ "--orbit": `${index * 23}deg` } as React.CSSProperties} /><span>{candidate.productType.replace(/-/g, " ")}</span><strong>{candidate.name}</strong><small>{included ? "In this configuration" : disabled ? `Selection limit of ${LIMIT}` : "Add catalog record"}</small></button>; })}</div></section>
    <section className={styles.composerFacts} aria-labelledby="composition-facts"><p className={styles.eyebrow}>Governed composition facts</p><h2 id="composition-facts">No invisible scoring or commercial math.</h2><dl className={styles.factMatrix}><div><dt>Combined price</dt><dd>Unavailable — no server-governed combined price record exists.</dd></div><div><dt>Cadence and savings</dt><dd>Unavailable — no server-governed combined billing or savings rule exists.</dd></div><div><dt>Compatibility</dt><dd>{facts.compatibility}</dd></div><div><dt>Prerequisites</dt><dd>{facts.prerequisites}</dd></div><div><dt>License scope</dt><dd>{facts.licenseScope}</dd></div><div><dt>Activation</dt><dd>{facts.activation}</dd></div></dl>{records.length ? <div className={styles.selectionList}>{records.map((record) => <div key={record.productId}><b>{initials(record.name)}</b><span><strong>{record.name}</strong><small>{record.family} · v{record.version} · {plain(record.installProfile)}</small></span><Link href={`/ai-marketplace/${encodeURIComponent(record.slug)}`}>Record facts</Link></div>)}</div> : <p className={styles.emptyState}>No catalog records selected. The composer will not manufacture a default bundle.</p>}<div className={styles.actions}>{records.length > 0 && <Link className={styles.primaryAction} href={`/contact?interest=ai-marketplace&products=${encodeURIComponent(records.map((record) => record.productId).join(","))}`}>Discuss this governed selection</Link>}{records.length > 0 && <Link className={styles.secondaryAction} href={`/ai-marketplace/compare?items=${encodeURIComponent(records.map((record) => record.slug).join(","))}`}>Compare selected records</Link>}<Link className={styles.secondaryAction} href="/ai-marketplace">Return to capability universe</Link></div></section>
  </>;
}
