"use client";

import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useMemo, useState } from "react";
import type { MarketplaceWorkspaceRecord } from "../../lib/marketplace-v12-workspaces";
import MarketplaceSpatialStage from "./MarketplaceSpatialStage";
import styles from "./MarketplaceWorkspaces.module.css";

const LIMIT = 4;
function offerText(record: MarketplaceWorkspaceRecord) { return record.pricing.offers.length ? record.pricing.offers.map((offer) => `${new Intl.NumberFormat("en-US", { style: "currency", currency: offer.currency }).format(offer.amount_minor / 100)}${offer.cadence && offer.cadence !== "one-time" ? ` / ${offer.cadence}` : " one-time"}`).join(" · ") : "Pricing available on request"; }
function stateText(value: string | null) { return value ? value.replace(/[-_]/g, " ") : "Not recorded"; }

export default function MarketplaceComparisonStage({ records, candidates, invalidReason }: { records: MarketplaceWorkspaceRecord[]; candidates: MarketplaceWorkspaceRecord[]; invalidReason: string | null }) {
  const router = useRouter(), pathname = usePathname(), params = useSearchParams();
  const [selectedId, setSelectedId] = useState<string | null>(records[0]?.productId ?? null);
  const selected = records.find((record) => record.productId === selectedId) ?? records[0] ?? null;
  const selectedIds = useMemo(() => new Set(records.map((record) => record.productId)), [records]);
  const replace = (next: MarketplaceWorkspaceRecord[]) => { const query = new URLSearchParams(params.toString()); if (next.length) query.set("items", next.map((record) => record.slug).sort().join(",")); else query.delete("items"); router.replace(`${pathname}${query.size ? `?${query}` : ""}`, { scroll: false }); };
  return <>
    <section className={styles.intro} aria-labelledby="comparison-title"><div><p className={styles.eyebrow}>Compare capabilities</p><h1 id="comparison-title">Compare up to four options side by side.</h1><p>Review categories, pricing, and product details to find the best fit for your goals.</p></div><aside><span>Your comparison</span><strong>{records.length} of {LIMIT} selected</strong><p>{records.length ? "Share this page or continue building your selection." : "Select capabilities below to begin."}</p></aside></section>
    {invalidReason && <p className={styles.alert} role="alert">We couldn&apos;t add that capability. Return to the marketplace and choose it again.</p>}
    <section className={styles.stageLayout} aria-labelledby="comparison-spatial-title"><div className={styles.stageCopy}><p className={styles.eyebrow}>Visual overview</p><h2 id="comparison-spatial-title">Explore your selected capabilities.</h2><p>{selected ? `${selected.name} is selected. Choose another capability in the visual or review its details.` : "Choose up to four capabilities to see them together."}</p>{selected && <Link className={styles.secondaryAction} href={`/ai-marketplace/${encodeURIComponent(selected.slug)}`}>View selected capability</Link>}</div><MarketplaceSpatialStage label="Marketplace capability comparison" nodes={records} selectedId={selected?.productId} onSelect={(node) => setSelectedId(node.productId)} emptyMessage="No capabilities are selected. Choose from the options below to start comparing." /></section>
    <section className={styles.selectorSection} aria-labelledby="compare-selection"><div><p className={styles.eyebrow}>Choose capabilities</p><h2 id="compare-selection">Add or remove options</h2><p>Select from the available capabilities below. Visit the marketplace to search for more.</p></div><div className={styles.selectorOrbit}>{candidates.map((candidate, index) => { const included = selectedIds.has(candidate.productId), disabled = !included && records.length >= LIMIT; return <button type="button" key={candidate.productId} className={included ? styles.selected : undefined} aria-pressed={included} disabled={disabled} onClick={() => replace(included ? records.filter((record) => record.productId !== candidate.productId) : [...records, candidate])}><i style={{ "--orbit": `${index * 27}deg` } as React.CSSProperties} /><span>{candidate.family}</span><strong>{candidate.name}</strong><small>{included ? "Included in comparison" : disabled ? `Comparison limit of ${LIMIT}` : "Add to comparison"}</small></button>; })}</div></section>
    {records.length > 0 && <section className={styles.comparisonTable} aria-labelledby="comparison-facts"><div><p className={styles.eyebrow}>At a glance</p><h2 id="comparison-facts">Capability comparison</h2></div><div className={styles.tableScroll}><table><caption>Details for your selected capabilities</caption><thead><tr><th scope="col">Compare</th>{records.map((record) => <th scope="col" key={record.productId}>{record.name}</th>)}</tr></thead><tbody><tr><th scope="row">Provider</th>{records.map((record) => <td key={record.productId}>{record.publisher}</td>)}</tr><tr><th scope="row">Category</th>{records.map((record) => <td key={record.productId}>{record.family}<br />{stateText(record.productType)}</td>)}</tr><tr><th scope="row">Price</th>{records.map((record) => <td key={record.productId}>{offerText(record)}</td>)}</tr><tr><th scope="row">Details</th>{records.map((record) => <td key={record.productId}><Link href={`/ai-marketplace/${encodeURIComponent(record.slug)}`}>View capability</Link></td>)}</tr></tbody></table></div><div className={styles.actions}><Link className={styles.primaryAction} href={`/ai-marketplace/configure?items=${encodeURIComponent(records.map((record) => record.slug).join(","))}`}>Continue with these capabilities</Link><Link className={styles.secondaryAction} href="/ai-marketplace">Back to marketplace</Link></div></section>}
  </>;
}
