"use client";

import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useMemo, useState } from "react";
import type { MarketplaceWorkspaceRecord } from "../../lib/marketplace-v12-workspaces";
import MarketplaceSpatialStage from "./MarketplaceSpatialStage";
import styles from "./MarketplaceWorkspaces.module.css";

const LIMIT = 4;
function offerText(record: MarketplaceWorkspaceRecord) { return record.pricing.offers.length ? record.pricing.offers.map((offer) => `${new Intl.NumberFormat("en-US", { style: "currency", currency: offer.currency }).format(offer.amount_minor / 100)}${offer.cadence ? ` / ${offer.cadence}` : " one-time"}`).join(" · ") : "Enterprise quote required"; }
function stateText(value: string | null) { return value ? value.replace(/[-_]/g, " ") : "Not recorded"; }

export default function MarketplaceComparisonStage({ records, candidates, invalidReason }: { records: MarketplaceWorkspaceRecord[]; candidates: MarketplaceWorkspaceRecord[]; invalidReason: string | null }) {
  const router = useRouter(), pathname = usePathname(), params = useSearchParams();
  const [selectedId, setSelectedId] = useState<string | null>(records[0]?.productId ?? null);
  const selected = records.find((record) => record.productId === selectedId) ?? records[0] ?? null;
  const selectedIds = useMemo(() => new Set(records.map((record) => record.productId)), [records]);
  const replace = (next: MarketplaceWorkspaceRecord[]) => { const query = new URLSearchParams(params.toString()); if (next.length) query.set("items", next.map((record) => record.slug).sort().join(",")); else query.delete("items"); router.replace(`${pathname}${query.size ? `?${query}` : ""}`, { scroll: false }); };
  return <>
    <section className={styles.intro} aria-labelledby="comparison-title"><div><p className={styles.eyebrow}>Comparison stage</p><h1 id="comparison-title">Compare real catalog records in one shareable view.</h1><p>Selection is validated on the server against the current catalog revision. Prices, release state, install mode, relationships, and availability are catalog facts—not inferred recommendations.</p></div><aside><span>Shareable state</span><strong>{records.length} / {LIMIT} records</strong><p>{records.length ? "This URL contains only stable catalog slugs." : "Select records to create a compact, reviewable URL."}</p></aside></section>
    {invalidReason && <p className={styles.alert} role="alert">{invalidReason}</p>}
    <section className={styles.stageLayout} aria-labelledby="comparison-spatial-title"><div className={styles.stageCopy}><p className={styles.eyebrow}>Spatial evidence</p><h2 id="comparison-spatial-title">Declared relationships, not invented affinity.</h2><p>{selected ? `${selected.name} is selected. Its plotted position and edges come from the current server catalog projection.` : "Choose up to four catalog records. The spatial stage will never create relationships that the catalog does not declare."}</p>{selected && <Link className={styles.secondaryAction} href={`/ai-marketplace/${encodeURIComponent(selected.slug)}`}>Open selected catalog record</Link>}</div><MarketplaceSpatialStage label="Marketplace comparison spatial stage" nodes={records} selectedId={selected?.productId} onSelect={(node) => setSelectedId(node.productId)} emptyMessage="No records are selected. Use the semantic selector below to build a server-validated comparison." /></section>
    <section className={styles.selectorSection} aria-labelledby="compare-selection"><div><p className={styles.eyebrow}>Validated selector</p><h2 id="compare-selection">Add or remove catalog records</h2><p>The first 24 server catalog results are offered here; use marketplace search for any other record, then open Compare from its detail route.</p></div><div className={styles.selectorOrbit}>{candidates.map((candidate, index) => { const included = selectedIds.has(candidate.productId), disabled = !included && records.length >= LIMIT; return <button type="button" key={candidate.productId} className={included ? styles.selected : undefined} aria-pressed={included} disabled={disabled} onClick={() => replace(included ? records.filter((record) => record.productId !== candidate.productId) : [...records, candidate])}><i style={{ "--orbit": `${index * 27}deg` } as React.CSSProperties} /><span>{candidate.family}</span><strong>{candidate.name}</strong><small>{included ? "Included in comparison" : disabled ? `Comparison limit of ${LIMIT}` : "Add to comparison"}</small></button>; })}</div></section>
    {records.length > 0 && <section className={styles.comparisonTable} aria-labelledby="comparison-facts"><div><p className={styles.eyebrow}>Server catalog facts</p><h2 id="comparison-facts">Side-by-side product record</h2></div><div className={styles.tableScroll}><table><caption>Current catalog facts for the selected records</caption><thead><tr><th scope="col">Field</th>{records.map((record) => <th scope="col" key={record.productId}>{record.name}</th>)}</tr></thead><tbody><tr><th scope="row">Publisher</th>{records.map((record) => <td key={record.productId}>{record.publisher}</td>)}</tr><tr><th scope="row">Family / type</th>{records.map((record) => <td key={record.productId}>{record.family}<br />{stateText(record.productType)}</td>)}</tr><tr><th scope="row">Version / release</th>{records.map((record) => <td key={record.productId}>v{record.version}<br />{record.releaseVersion ? `Current release v${record.releaseVersion}` : "No release record"}</td>)}</tr><tr><th scope="row">Catalog guidance</th>{records.map((record) => <td key={record.productId}>{offerText(record)}</td>)}</tr><tr><th scope="row">Install mode</th>{records.map((record) => <td key={record.productId}>{stateText(record.installProfile)}<br />{record.installBridgeEnabled ? "Bridge marked enabled by catalog" : record.installFallbackLabel ?? "No install bridge published"}</td>)}</tr><tr><th scope="row">Declared links</th>{records.map((record) => <td key={record.productId}>{record.relationshipProductIds.length}</td>)}</tr><tr><th scope="row">Current action</th>{records.map((record) => <td key={record.productId}>{record.action.label}<br /><small>{record.action.reasonCode ? stateText(record.action.reasonCode) : "No enabled commerce action"}</small></td>)}</tr></tbody></table></div><div className={styles.actions}><Link className={styles.primaryAction} href={`/ai-marketplace/configure?items=${encodeURIComponent(records.map((record) => record.slug).join(","))}`}>Configure this factual selection</Link><Link className={styles.secondaryAction} href="/ai-marketplace">Return to capability universe</Link></div></section>}
  </>;
}
