"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import type { MarketplaceV12Card } from "../../lib/marketplace-v12-catalog";

function offerLabel(offer: MarketplaceV12Card["pricing"]["offers"][number]) {
  const amount = new Intl.NumberFormat("en-US", { style: "currency", currency: offer.currency }).format(offer.amount_minor / 100);
  const kind = offer.kind.replace(/[_-]/g, " ");
  return `${amount}${offer.cadence ? ` / ${offer.cadence}` : ""} · ${kind}`;
}

export default function MarketplacePedestal({ product }: { product: MarketplaceV12Card }) {
  const offers = product.pricing.offers ?? [], [selected, setSelected] = useState(0), [comparison, setComparison] = useState(false);
  const current = offers[selected]; const relationships = product.visualization.relationship_product_ids ?? [];
  const priceBasis = useMemo(() => { const value = (product.pricing as { pricing_basis?: unknown }).pricing_basis; return typeof value === "string" ? value : "Catalog-supplied commercial guidance"; }, [product.pricing]);
  return <section className="ai-marketplace__pedestal" aria-labelledby="product-configuration-heading"><div className="ai-marketplace__pedestal-stage" aria-hidden="true"><div className="ai-marketplace__pedestal-orbit" /><div className="ai-marketplace__pedestal-core"><span>{product.product_type.replace(/-/g, " ")}</span><strong>v{product.version}</strong></div></div><div className="ai-marketplace__pedestal-panel"><p className="ai-marketplace__eyebrow">Catalog record pedestal</p><h2 id="product-configuration-heading">Inspect catalog configuration</h2><p>This is a read-only catalog configuration. Selecting an offer changes guidance only; it does not create a checkout, entitlement, installation, or reservation.</p>{offers.length > 0 ? <fieldset><legend>Catalog-supplied offer options</legend><div className="ai-marketplace__offer-options">{offers.map((offer, index) => <label key={`${offer.kind}-${offer.amount_minor}-${offer.cadence ?? "once"}`}><input type="radio" name="catalog-offer" checked={selected === index} onChange={() => setSelected(index)} /><span>{offerLabel(offer)}</span></label>)}</div></fieldset> : <p className="ai-marketplace__pedestal-unavailable">No offer options are published in this catalog record.</p>}<div className="ai-marketplace__configuration-readout"><span>Selected guidance</span><strong>{current ? offerLabel(current) : "Unavailable"}</strong><small>Basis: {priceBasis}</small></div>{offers.length > 1 && <button type="button" className="ai-marketplace__compare" aria-expanded={comparison} onClick={() => setComparison((value) => !value)}>{comparison ? "Hide offer comparison" : "Compare catalog offers"}</button>}{comparison && <div className="ai-marketplace__comparison" aria-label="Catalog offer comparison"><table><caption>Catalog-supplied offer comparison</caption><thead><tr><th scope="col">Offer</th><th scope="col">Cadence</th><th scope="col">Catalog state</th></tr></thead><tbody>{offers.map((offer) => <tr key={`${offer.kind}-${offer.amount_minor}-${offer.cadence ?? "once"}`}><td>{offerLabel(offer)}</td><td>{offer.cadence ?? "one-time"}</td><td>{product.publication_state.replace(/-/g, " ")}</td></tr>)}</tbody></table></div>}<dl className="ai-marketplace__pedestal-facts"><div><dt>Delivery</dt><dd>Protected delivery unavailable until entitlement and release controls are verified.</dd></div><div><dt>Installation</dt><dd>Install bridge unavailable; no destination is configured from this catalog view.</dd></div><div><dt>Related records</dt><dd>{relationships.length ? `${relationships.length} catalog-declared relationships` : "No catalog-declared relationships"}</dd></div></dl><div className="ai-marketplace__pedestal-actions"><Link href={`/contact?interest=ai-marketplace&product=${encodeURIComponent(product.product_id)}`}>Discuss enterprise licensing</Link><Link href="/ai-marketplace/hangar">Open customer hangar status</Link></div></div></section>;
}
