-- Isolated, service-role-only authority for marketplace payment fulfillment.
create schema if not exists obserra_ai_marketplace;
create table if not exists obserra_ai_marketplace.customers(subject_id text not null,tenant_id text not null,stripe_customer_id text not null unique,primary key(subject_id,tenant_id));
create table if not exists obserra_ai_marketplace.checkout_attempts(attempt_id uuid primary key,request_key text not null unique,subject_id text not null,tenant_id text not null,product_id text not null,billing_interval text not null check(billing_interval in('monthly','annual','one-time')),stripe_customer_id text,stripe_checkout_session_id text unique,issued_at bigint not null,expires_at bigint not null,check(expires_at>issued_at));
create table if not exists obserra_ai_marketplace.payment_events(stripe_event_id text primary key,event_type text not null,payload_sha256 text not null,livemode boolean not null,stripe_checkout_session_id text not null,created_at timestamptz not null default now());
create table if not exists obserra_ai_marketplace.entitlements(subject_id text not null,tenant_id text not null,product_id text not null,billing_interval text not null,stripe_customer_id text not null,stripe_checkout_session_id text not null unique,stripe_price_id text not null,access_status text not null check(access_status in('active','revoked')),revision integer not null default 1,updated_at timestamptz not null default now(),primary key(subject_id,tenant_id,product_id));
alter table obserra_ai_marketplace.customers enable row level security; alter table obserra_ai_marketplace.checkout_attempts enable row level security; alter table obserra_ai_marketplace.payment_events enable row level security; alter table obserra_ai_marketplace.entitlements enable row level security;
create or replace function public.obserra_ai_marketplace_customer(p_subject_id text,p_tenant_id text) returns jsonb language sql security definer set search_path=pg_catalog,obserra_ai_marketplace as $$select coalesce((select jsonb_build_object('stripeCustomerId',stripe_customer_id) from obserra_ai_marketplace.customers where subject_id=p_subject_id and tenant_id=p_tenant_id),'null'::jsonb)$$;
create or replace function public.obserra_ai_marketplace_bind_customer(p_subject_id text,p_tenant_id text,p_stripe_customer_id text) returns jsonb language plpgsql security definer set search_path=pg_catalog,obserra_ai_marketplace as $$begin insert into obserra_ai_marketplace.customers values(p_subject_id,p_tenant_id,p_stripe_customer_id) on conflict(subject_id,tenant_id) do update set stripe_customer_id=excluded.stripe_customer_id;return jsonb_build_object('stripeCustomerId',p_stripe_customer_id);end$$;
create or replace function public.obserra_ai_marketplace_reserve_checkout(p_attempt_id uuid,p_request_key text,p_subject_id text,p_tenant_id text,p_product_id text,p_billing_interval text,p_issued_at bigint,p_expires_at bigint) returns jsonb language plpgsql security definer set search_path=pg_catalog,obserra_ai_marketplace as $$declare v obserra_ai_marketplace.checkout_attempts%rowtype;begin select * into v from obserra_ai_marketplace.checkout_attempts where request_key=p_request_key and expires_at>=extract(epoch from now())::bigint for update;if found then return jsonb_build_object('attemptId',v.attempt_id::text,'stripeCustomerId',v.stripe_customer_id,'stripeSessionId',v.stripe_checkout_session_id);end if;insert into obserra_ai_marketplace.checkout_attempts values(p_attempt_id,p_request_key,p_subject_id,p_tenant_id,p_product_id,p_billing_interval,null,null,p_issued_at,p_expires_at) returning * into v;return jsonb_build_object('attemptId',v.attempt_id::text,'stripeCustomerId',null,'stripeSessionId',null);end$$;
create or replace function public.obserra_ai_marketplace_record_checkout(p_attempt_id uuid,p_stripe_customer_id text,p_stripe_checkout_session_id text) returns jsonb language plpgsql security definer set search_path=pg_catalog,obserra_ai_marketplace as $$begin update obserra_ai_marketplace.checkout_attempts set stripe_customer_id=p_stripe_customer_id,stripe_checkout_session_id=p_stripe_checkout_session_id where attempt_id=p_attempt_id and stripe_checkout_session_id is null;if not found then raise exception 'checkout unavailable';end if;return jsonb_build_object('attemptId',p_attempt_id::text);end$$;
create or replace function public.obserra_ai_marketplace_entitlement(p_subject_id text,p_tenant_id text,p_product_id text) returns jsonb language sql security definer set search_path=pg_catalog,obserra_ai_marketplace as $$select coalesce((select jsonb_build_object('allowed',access_status='active') from obserra_ai_marketplace.entitlements where subject_id=p_subject_id and tenant_id=p_tenant_id and product_id=p_product_id),jsonb_build_object('allowed',false))$$;
create or replace function public.obserra_ai_marketplace_record_payment(p_event_id text,p_event_type text,p_payload_sha256 text,p_livemode boolean,p_stripe_checkout_session_id text,p_stripe_customer_id text,p_subject_id text,p_tenant_id text,p_product_id text,p_billing_interval text,p_stripe_price_id text) returns jsonb language plpgsql security definer set search_path=pg_catalog,obserra_ai_marketplace as $$declare a obserra_ai_marketplace.checkout_attempts%rowtype;begin select * into a from obserra_ai_marketplace.checkout_attempts where stripe_checkout_session_id=p_stripe_checkout_session_id for update;if not found or a.subject_id<>p_subject_id or a.tenant_id<>p_tenant_id or a.product_id<>p_product_id or a.billing_interval<>p_billing_interval or a.stripe_customer_id<>p_stripe_customer_id then raise exception 'payment authority mismatch';end if;insert into obserra_ai_marketplace.payment_events values(p_event_id,p_event_type,p_payload_sha256,p_livemode,p_stripe_checkout_session_id) on conflict(stripe_event_id) do nothing;if not found then return jsonb_build_object('idempotentReplay',true);end if;insert into obserra_ai_marketplace.entitlements(subject_id,tenant_id,product_id,billing_interval,stripe_customer_id,stripe_checkout_session_id,stripe_price_id,access_status) values(p_subject_id,p_tenant_id,p_product_id,p_billing_interval,p_stripe_customer_id,p_stripe_checkout_session_id,p_stripe_price_id,'active') on conflict(subject_id,tenant_id,product_id) do update set access_status='active',stripe_customer_id=excluded.stripe_customer_id,stripe_checkout_session_id=excluded.stripe_checkout_session_id,stripe_price_id=excluded.stripe_price_id,revision=obserra_ai_marketplace.entitlements.revision+1,updated_at=now();return jsonb_build_object('recorded',true);end$$;
create or replace function public.obserra_ai_marketplace_commerce_health() returns jsonb language sql security definer set search_path=pg_catalog,obserra_ai_marketplace as $$select jsonb_build_object('operational',true,'entitlementAuthority','ai-marketplace-commerce-ledger-v1')$$;
create or replace function public.obserra_ai_marketplace_revoke_entitlement(p_event_id text,p_stripe_checkout_session_id text,p_reason text) returns jsonb language plpgsql security definer set search_path=pg_catalog,obserra_ai_marketplace as $$begin insert into obserra_ai_marketplace.payment_events values(p_event_id,p_reason,repeat('0',64),true,p_stripe_checkout_session_id) on conflict(stripe_event_id) do nothing;if not found then return jsonb_build_object('idempotentReplay',true);end if;update obserra_ai_marketplace.entitlements set access_status='revoked',revision=revision+1,updated_at=now() where stripe_checkout_session_id=p_stripe_checkout_session_id;return jsonb_build_object('revoked',found);end$$;
revoke all on schema obserra_ai_marketplace from public; revoke all on all tables in schema obserra_ai_marketplace from public,anon,authenticated; revoke all on function public.obserra_ai_marketplace_customer(text,text),public.obserra_ai_marketplace_bind_customer(text,text,text),public.obserra_ai_marketplace_reserve_checkout(uuid,text,text,text,text,text,bigint,bigint),public.obserra_ai_marketplace_record_checkout(uuid,text,text) from public,anon,authenticated; grant execute on function public.obserra_ai_marketplace_customer(text,text),public.obserra_ai_marketplace_bind_customer(text,text,text),public.obserra_ai_marketplace_reserve_checkout(uuid,text,text,text,text,text,bigint,bigint),public.obserra_ai_marketplace_record_checkout(uuid,text,text) to service_role;
revoke all on function public.obserra_ai_marketplace_entitlement(text,text,text),public.obserra_ai_marketplace_record_payment(text,text,text,boolean,text,text,text,text,text,text,text) from public,anon,authenticated; grant execute on function public.obserra_ai_marketplace_entitlement(text,text,text),public.obserra_ai_marketplace_record_payment(text,text,text,boolean,text,text,text,text,text,text,text) to service_role;
revoke all on function public.obserra_ai_marketplace_commerce_health() from public,anon,authenticated; grant execute on function public.obserra_ai_marketplace_commerce_health() to service_role;
revoke all on function public.obserra_ai_marketplace_revoke_entitlement(text,text,text) from public,anon,authenticated; grant execute on function public.obserra_ai_marketplace_revoke_entitlement(text,text,text) to service_role;
