import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { auth } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import { getStripe } from "../../../lib/stripe";
import { primaryAccountEmail } from "../../../lib/app-entitlements";
import "./orders.css";

export const metadata: Metadata = {
  title: "Orders and Billing | Obserra Customer Portal",
  description: "Review verified Obserra subscriptions, invoices, receipts, and fulfillment pathways.",
  robots: { index: false, follow: false },
};

export const dynamic = "force-dynamic";

function money(amount: number | null, currency: string | null) {
  if (amount === null || !currency) return "Not available";
  return new Intl.NumberFormat("en-US", { style: "currency", currency: currency.toUpperCase() }).format(amount / 100);
}

function dateFromUnix(value: number | null | undefined) {
  if (!value) return "Not available";
  return new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(new Date(value * 1000));
}

export default async function OrdersPage() {
  const { userId } = await auth();
  if (!userId) redirect("/sign-in?redirect_url=/portal/orders");

  const email = await primaryAccountEmail();
  if (!process.env.STRIPE_SECRET_KEY || !email) {
    return (
      <main className="orders-page">
        <header className="orders-nav"><Link href="/" className="orders-brand"><Image src="/brand/obserra-logo.png" alt="Obserra Executive Protection and Intelligence LLC" width={286} height={55} /><span>ORDERS &amp; BILLING</span></Link><nav><Link href="/store">Store</Link><Link href="/portal/applications">Applications</Link><Link href="/portal">Dashboard</Link></nav></header>
        <section className="orders-empty"><p>VERIFIED COMMERCE RECORDS</p><h1>Billing records are unavailable.</h1><span>The portal is configured to fail closed when Stripe or the verified account email is unavailable. No simulated orders or balances are displayed.</span></section>
      </main>
    );
  }

  const stripe = getStripe();
  const customers = await stripe.customers.list({ email, limit: 10 });
  const customerIds = customers.data.map((customer) => customer.id);
  const subscriptionGroups = await Promise.all(customerIds.map((customer) => stripe.subscriptions.list({ customer, status: "all", limit: 100, expand: ["data.items.data.price.product"] })));
  const invoiceGroups = await Promise.all(customerIds.map((customer) => stripe.invoices.list({ customer, limit: 100 })));
  const subscriptions = subscriptionGroups.flatMap((group) => group.data).sort((a, b) => b.created - a.created);
  const invoices = invoiceGroups.flatMap((group) => group.data).sort((a, b) => b.created - a.created);
  const activeCount = subscriptions.filter((subscription) => subscription.status === "active" || subscription.status === "trialing").length;

  return (
    <main className="orders-page">
      <header className="orders-nav"><Link href="/" className="orders-brand"><Image src="/brand/obserra-logo.png" alt="Obserra Executive Protection and Intelligence LLC" width={286} height={55} /><span>ORDERS &amp; BILLING</span></Link><nav><Link href="/store">Store</Link><Link href="/portal/applications">Applications</Link><Link href="/portal">Dashboard</Link><a className="orders-cta" href="/api/apps/billing-portal">Manage billing</a></nav></header>

      <section className="orders-hero"><p>AUTHENTICATED COMMERCE CENTER</p><h1>Your verified subscriptions, invoices, receipts, and fulfillment pathways.</h1><span>Records are loaded directly from Stripe using your authenticated Obserra account. No order, invoice, subscription, balance, or receipt is generated by the website.</span></section>

      <section className="orders-kpis"><article><small>ACTIVE SUBSCRIPTIONS</small><strong>{activeCount}</strong><span>Active or trialing</span></article><article><small>TOTAL SUBSCRIPTIONS</small><strong>{subscriptions.length}</strong><span>All Stripe states</span></article><article><small>INVOICES</small><strong>{invoices.length}</strong><span>Verified billing records</span></article><article><small>PAYMENT SYSTEM</small><strong>Stripe</strong><span>Hosted checkout and billing</span></article></section>

      <section className="orders-section"><div className="orders-heading"><div><p>SUBSCRIPTIONS</p><h2>Current and historical recurring purchases.</h2></div><span>Application fulfillment is available only when entitlement status is active or trialing.</span></div>
        {subscriptions.length ? <div className="orders-grid">{subscriptions.map((subscription) => { const item = subscription.items.data[0]; const product = item && typeof item.price.product !== "string" ? item.price.product : null; const appSlug = subscription.metadata.obserraApp; return <article key={subscription.id}><header><small>{subscription.status.toUpperCase()}</small><strong>{product?.name || appSlug || "Obserra subscription"}</strong></header><dl><div><dt>Plan</dt><dd>{subscription.metadata.plan || item?.price.recurring?.interval || "Not available"}</dd></div><div><dt>Deployment</dt><dd>{subscription.metadata.deploymentModel || "Not specified"}</dd></div><div><dt>Started</dt><dd>{dateFromUnix(subscription.start_date)}</dd></div><div><dt>Current period</dt><dd>{dateFromUnix(subscription.current_period_end)}</dd></div></dl><footer>{appSlug ? <Link href="/portal/applications">Open fulfillment</Link> : <Link href="/store">View offering</Link>}<a href="/api/apps/billing-portal">Manage subscription</a></footer></article>; })}</div> : <div className="orders-empty-card"><h3>No Stripe subscriptions found.</h3><p>This account has no recurring purchase records associated with the verified email address.</p><Link href="/store">Browse the store</Link></div>}
      </section>

      <section className="orders-section"><div className="orders-heading"><div><p>INVOICES &amp; RECEIPTS</p><h2>Verified payment and billing documents.</h2></div><span>Links are provided only when Stripe returns a hosted invoice or invoice PDF.</span></div>
        {invoices.length ? <div className="invoice-list">{invoices.map((invoice) => <article key={invoice.id}><div><small>{(invoice.status || "unknown").toUpperCase()}</small><strong>{invoice.number || invoice.id}</strong><span>{dateFromUnix(invoice.created)}</span></div><div><strong>{money(invoice.amount_paid, invoice.currency)}</strong><span>Paid</span></div><div className="invoice-actions">{invoice.hosted_invoice_url ? <a href={invoice.hosted_invoice_url} target="_blank" rel="noreferrer">View invoice</a> : null}{invoice.invoice_pdf ? <a href={invoice.invoice_pdf} target="_blank" rel="noreferrer">Download PDF</a> : null}</div></article>)}</div> : <div className="orders-empty-card"><h3>No Stripe invoices found.</h3><p>No verified invoices are associated with this authenticated account.</p></div>}
      </section>
    </main>
  );
}
