import type { Metadata } from "next";
import Image from "next/image";
import "./home.css";

export const metadata: Metadata = {
  title: "Enterprise Intelligence, Protection, Cybersecurity & Training",
  description: "Obserra brings enterprise intelligence, secure AI native application development, cybersecurity leadership, protective intelligence, and practical professional training together for organizations and leaders who need disciplined action.",
  alternates: { canonical: "/" },
};

const divisions = [
  { number: "01", title: "EIOS", eyebrow: "Enterprise intelligence operating system", copy: "A governed enterprise intelligence experience for leaders who need stronger visibility, better decisions, and accountable outcomes.", cta: "Explore EIOS", href: "/eios", tone: "signal" },
  { number: "02", title: "Cybersecurity", eyebrow: "Strategy, governance, and resilience", copy: "Executive cybersecurity strategy, cyber risk visibility, incident readiness, governance, and board ready advisory services.", cta: "Explore cybersecurity", href: "#cyber", tone: "blue" },
  { number: "03", title: "Protection & Intelligence", eyebrow: "Protective intelligence and risk advisory", copy: "Executive protection, travel risk, digital exposure reviews, protective intelligence, and discreet risk support for people and organizations.", cta: "Explore protection", href: "#protection", tone: "gold" },
  { number: "04", title: "Obserra Academy", eyebrow: "Paid professional training", copy: "Interactive learning across cybersecurity, protection, intelligence, and Obserra Technologies with a 25 question assessment and Obserra Certificate of Training after successful completion.", cta: "View all courses", href: "/academy", tone: "academy" },
];

const courseTracks = [
  ["Cybersecurity", "Security foundations, phishing defense, incident response, NIST, CMMC awareness, executive governance, and AI security."],
  ["Protection", "Executive protection, protective intelligence, travel risk, and operational preparedness."],
  ["Intelligence", "Intelligence analysis, executive briefing, OSINT, and digital exposure awareness."],
  ["Obserra Technologies", "EIOS foundations, secure AI integration, and custom AI native application strategy for modern enterprise leaders."],
];

export default function HomePage() {
  return <main className="obserra-home">
    <header className="home-nav"><a href="/" className="home-brand"><Image src="/brand/obserra-logo.png" width={248} height={48} priority alt="Obserra Executive Protection and Intelligence LLC" /></a><nav><a href="#divisions">What we do</a><a href="/eios">EIOS</a><a href="#technologies">Technologies</a><a href="/academy">Academy</a><a href="/about">About</a><a href="/sign-in" className="home-nav-login">Learner sign in</a><a href="#connect" className="home-nav-cta">Talk with Obserra</a></nav></header>

    <section className="home-hero"><div className="home-grid" /><div className="hero-copy"><p className="home-eyebrow">VETERAN OWNED Â· PROPERTY OF OBSERRA</p><h1>See the risk.<br /><em>Lead the response.</em></h1><p>Obserra combines enterprise intelligence, secure AI native application development, cybersecurity leadership, protective intelligence, and professional training to help leaders move from uncertainty to disciplined action.</p><div className="home-actions"><a className="home-button" href="/academy">Explore Obserra Academy <span>â†’</span></a><a className="home-link" href="/eios">Discover EIOS <span>â†’</span></a></div></div><aside className="hero-proof"><p>BUILT FOR THE DECISIONS THAT CANNOT WAIT</p><div><strong>Enterprise intelligence</strong><span>Context, accountability, and decision clarity.</span></div><div><strong>AI native applications</strong><span>Custom tools built around the business outcome.</span></div><div><strong>Cyber resilience</strong><span>Strategy, governance, and readiness.</span></div><div><strong>Protective intelligence</strong><span>People, travel, digital exposure, and risk.</span></div><div><strong>Professional training</strong><span>Paid, interactive, certificate based learning.</span></div></aside></section>

    <section className="trust-rail" aria-label="Obserra engagement standards"><article><span>01</span><p>EXECUTIVE READY</p><strong>Clear decisions for leaders, boards, and high consequence operations.</strong></article><article><span>02</span><p>SECURE BY DESIGN</p><strong>Confidentiality, accountability, and operational discipline from the beginning.</strong></article><article><span>03</span><p>BUILT TO MOVE</p><strong>Advisory, technology, protection, and training that turn strategy into action.</strong></article></section>

    <section className="home-intro" id="divisions"><p className="home-eyebrow">THE OBSERRA ADVANTAGE</p><h2>One trusted partner across risk, intelligence, action, and learning.</h2><p>Obserra is built for executives, organizations, and professionals who want practical expertise with a disciplined, accountable approach, not surface level advice or disconnected tools.</p></section>

    <section className="division-grid">{divisions.map((division) => <article className={`division-card ${division.tone}`} key={division.title}><span>{division.number}</span><p>{division.eyebrow}</p><h3>{division.title}</h3><div className="division-rule" /><strong>{division.copy}</strong><a href={division.href}>{division.cta} <b>â†’</b></a></article>)}</section>

    <section className="home-service" id="cyber"><div><p className="home-eyebrow">CYBERSECURITY &amp; RISK ADVISORY</p><h2>Make cyber risk a leadership advantage.</h2><p>From executive cyber leadership and cyber risk assessments to governance, policy design, incident readiness, and board communication, Obserra helps organizations turn security complexity into clear executive action.</p><a className="home-button" href="#connect">Discuss your cyber priorities <span>â†’</span></a></div><div className="service-signals"><span>Cyber risk strategy</span><span>Executive &amp; board briefings</span><span>Incident readiness</span><span>Governance &amp; policy</span><span>Digital exposure reviews</span><span>Security transformation</span></div></section>

    <section className="engagement-panel"><div><p className="home-eyebrow">THE OBSERRA ENGAGEMENT MODEL</p><h2>Start with the problem that matters most.</h2><p>Engage Obserra for an executive priority, a focused security challenge, a technology initiative, a protective intelligence need, or a workforce training requirement. The right entry point becomes a disciplined plan, clear next steps, and an experience designed around your organization.</p></div><div className="engagement-steps"><article><span>01</span><h3>Frame the decision</h3><p>Clarify the risk, priority, outcome, and decision owner.</p></article><article><span>02</span><h3>Design the response</h3><p>Bring together intelligence, expertise, and secure execution.</p></article><article><span>03</span><h3>Build lasting capability</h3><p>Equip leaders and teams with practical tools and training.</p></article></div></section>

    <section className="home-service technology-service" id="technologies"><div><p className="home-eyebrow">OBSERRA TECHNOLOGIES Â· AI NATIVE APPLICATIONS</p><h2>Build the AI native application your business actually needs.</h2><p>Obserra designs custom AI native applications, intelligent workflows, dashboards, and decision experiences around the business problem, not a generic template. Each engagement can integrate with EIOS as the intelligence and governance layer while respecting your data boundaries, operating model, confidentiality, and security requirements.</p><p className="technology-emphasis">From one executive workflow to a multi function operating experience, we turn high value business problems into governed solutions people will use.</p><a className="home-button" href="mailto:info@obserrallc.com?subject=Custom%20AI%20Native%20Application%20Consultation">Discuss your application <span>â†’</span></a></div><div className="service-signals"><span>AI native application design</span><span>EIOS integrated workflows</span><span>Secure data &amp; identity patterns</span><span>Custom portals &amp; dashboards</span><span>Enterprise automation</span><span>Decision intelligence</span></div></section>

    <section className="holographic-showcase"><div className="holo-visual" aria-label="Illustration of Obserra EIOS intelligence view"><div className="holo-ring ring-one" /><div className="holo-ring ring-two" /><div className="holo-ring ring-three" /><div className="holo-core"><span>OBSERRA</span><strong>EIOS</strong><small>GOVERNED INTELLIGENCE</small></div><div className="holo-node node-one">RISK<br /><b>CONTEXT</b></div><div className="holo-node node-two">EVIDENCE<br /><b>TRACEABILITY</b></div><div className="holo-node node-three">ACTION<br /><b>ACCOUNTABILITY</b></div></div><div className="holo-copy"><p className="home-eyebrow">THE EIOS VISUAL EXPERIENCE</p><h2>Turn complex intelligence into an executive level view.</h2><p>EIOS gives leaders a refined visual way to explore enterprise context, risk, evidence, policy, approvals, and accountable action. It is designed to make important conversations clearer, not to overwhelm people with another dashboard.</p><div className="holo-proof"><span>Executive visual briefings</span><span>Interactive intelligence views</span><span>Governed decision pathways</span></div><a className="home-button" href="/eios">Explore EIOS <span>â†’</span></a></div></section>

    <section className="academy-home" id="academy"><div className="academy-heading"><p className="home-eyebrow">OBSERRA ACADEMY</p><h2>Training that gives people a stronger next move.</h2><p>Choose a paid, self paced course designed around realistic decisions, not passive slides. Every course includes interactive lessons, real world context, learning checks, a 25 question final assessment, and an Obserra Certificate of Training for learners who meet the completion standard.</p><a className="home-button" href="/academy">Browse the Academy <span>â†’</span></a></div><div className="track-grid">{courseTracks.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p><a href="/academy">See courses â†’</a></article>)}</div><small>Courses are proprietary Obserra training. Completion certificates record successful training completion and do not grant licensure, accredited academic credit, or third party certification.</small></section>

    <section className="home-connect" id="connect"><p className="home-eyebrow">START WITH THE RIGHT CONVERSATION</p><h2>Protect what matters.<br />Build what lasts.</h2><p>Whether you are strengthening cyber resilience, protecting people and operations, building enterprise intelligence, or developing your team, Obserra is ready to engage.</p><div><a className="home-button" href="mailto:info@obserrallc.com?subject=Obserra%20Consultation">Schedule a consultation <span>â†’</span></a><a className="home-outline" href="/academy">Explore Academy courses <span>â†’</span></a></div></section>

    <footer className="home-footer"><Image src="/brand/obserra-logo.png" width={180} height={35} alt="Obserra Executive Protection and Intelligence LLC" /><p>Â© Obserra Executive Protection &amp; Intelligence LLC. Obserra, EIOS, Academy materials, and related visual and product content are proprietary to Obserra. Unauthorized reproduction, distribution, or use is prohibited.</p></footer>
  </main>;
}

