import "server-only";
import { createHmac, randomUUID } from "node:crypto";
import { ensureApplicationsRuntimeSecrets } from "./production-runtime-secrets";
const SUBJECT=/^user_[A-Za-z0-9_-]{8,}$/, TENANT=/^(?:org_[A-Za-z0-9_-]{8,}|subject:user_[A-Za-z0-9_-]{8,})$/, CUSTOMER=/^cus_[A-Za-z0-9]+$/, SESSION=/^cs_(?:live|test)_[A-Za-z0-9_]+$/;
export class AiMarketplaceCommerceError extends Error { constructor(message:string,readonly status=503){super(message);} }
function config(){const url=process.env.OBSERRA_APPLICATIONS_SUPABASE_URL?.trim()??"",key=process.env.OBSERRA_APPLICATIONS_SUPABASE_SERVICE_ROLE_KEY?.trim()??"";const parsed=new URL(url);if(parsed.protocol!=="https:"||parsed.hostname!=="ykmrlcfitsubqajgfnye.supabase.co"||!key)throw new AiMarketplaceCommerceError("Marketplace durable commerce is not configured.");return {url:parsed.origin,key,jwt:key.split(".").length===3};}
async function rpc<T>(name:string,body:Record<string,unknown>){await ensureApplicationsRuntimeSecrets();const c=config();const r=await fetch(`${c.url}/rest/v1/rpc/${name}`,{method:"POST",cache:"no-store",redirect:"error",headers:{apikey:c.key,...(c.jwt?{authorization:`Bearer ${c.key}`}:{ }),"content-type":"application/json",accept:"application/json"},body:JSON.stringify(body),signal:AbortSignal.timeout(10_000)});if(!r.ok)throw new AiMarketplaceCommerceError("Marketplace durable commerce is unavailable.",r.status);try{return await r.json() as T;}catch{throw new AiMarketplaceCommerceError("Marketplace durable commerce returned invalid data.");}}
function identity(subject:string,tenant:string){if(!SUBJECT.test(subject)||!TENANT.test(tenant))throw new AiMarketplaceCommerceError("Marketplace purchaser identity is invalid.",400);}
export function aiMarketplaceTenantId(subject:string,org?:string|null){const tenant=org||`subject:${subject}`;identity(subject,tenant);return tenant;}
function secret(){const value=process.env.OBSERRA_APPLICATIONS_COMMERCE_HASH_SECRET?.trim()??"";if(value.length<32)throw new AiMarketplaceCommerceError("Marketplace checkout hashing is not configured.");return value;}
export function aiMarketplaceCustomerKey(subject:string,tenant:string){identity(subject,tenant);return `ai-marketplace-customer-v1-${createHmac("sha256",secret()).update(`${subject}:${tenant}`).digest("hex")}`;}
export async function aiMarketplaceCustomer(subject:string,tenant:string){identity(subject,tenant);const v=await rpc<{stripeCustomerId:string}|null>("obserra_ai_marketplace_customer",{p_subject_id:subject,p_tenant_id:tenant});if(v&&!CUSTOMER.test(v.stripeCustomerId))throw new AiMarketplaceCommerceError("Marketplace customer record is invalid.");return v;}
export async function bindAiMarketplaceCustomer(subject:string,tenant:string,customer:string){identity(subject,tenant);if(!CUSTOMER.test(customer))throw new AiMarketplaceCommerceError("Marketplace customer is invalid.",400);return rpc<{stripeCustomerId:string}>("obserra_ai_marketplace_bind_customer",{p_subject_id:subject,p_tenant_id:tenant,p_stripe_customer_id:customer});}
export async function reserveAiMarketplaceCheckout(input:{subjectId:string;tenantId:string;productId:string;interval:string}){identity(input.subjectId,input.tenantId);const issued=Math.floor(Date.now()/1000),requestKey=createHmac("sha256",secret()).update(JSON.stringify(["ai-marketplace-checkout-v1",input.subjectId,input.tenantId,input.productId,input.interval,Math.floor(issued/900)])).digest("hex");const v=await rpc<{attemptId:string;stripeCustomerId:string|null;stripeSessionId:string|null}>("obserra_ai_marketplace_reserve_checkout",{p_attempt_id:randomUUID(),p_request_key:requestKey,p_subject_id:input.subjectId,p_tenant_id:input.tenantId,p_product_id:input.productId,p_billing_interval:input.interval,p_issued_at:issued,p_expires_at:issued+1800});if(!/^[0-9a-f-]{36}$/.test(v?.attemptId??"")||(v.stripeCustomerId!==null&&!CUSTOMER.test(v.stripeCustomerId))||(v.stripeSessionId!==null&&!SESSION.test(v.stripeSessionId)))throw new AiMarketplaceCommerceError("Marketplace checkout reservation is invalid.");return v;}
export async function recordAiMarketplaceCheckout(attempt:string,customer:string,session:string){if(!CUSTOMER.test(customer)||!SESSION.test(session))throw new AiMarketplaceCommerceError("Marketplace checkout provider identity is invalid.",400);return rpc("obserra_ai_marketplace_record_checkout",{p_attempt_id:attempt,p_stripe_customer_id:customer,p_stripe_checkout_session_id:session});}
export async function aiMarketplaceEntitlement(subject:string,tenant:string,product:string){identity(subject,tenant);return rpc<{allowed:boolean}>("obserra_ai_marketplace_entitlement",{p_subject_id:subject,p_tenant_id:tenant,p_product_id:product});}
export async function marketplaceV12DeliveryEntitlement(subject:string,tenant:string,product:string,revision:string,artifactSha256:string){identity(subject,tenant);if(!/^[a-f0-9]{64}$/.test(revision)||!/^[a-f0-9]{64}$/.test(artifactSha256))throw new AiMarketplaceCommerceError("Marketplace delivery identity is invalid.",400);return rpc<{allowed:boolean}>("obserra_ai_marketplace_v12_delivery_entitlement",{p_subject_id:subject,p_tenant_id:tenant,p_product_id:product,p_catalog_revision:revision,p_artifact_sha256:artifactSha256});}
export async function recordAiMarketplacePayment(v:{eventId:string;eventType:string;payload:string;live:boolean;session:string;customer:string;subject:string;tenant:string;product:string;interval:string;price:string}){return rpc("obserra_ai_marketplace_record_payment",{p_event_id:v.eventId,p_event_type:v.eventType,p_payload_sha256:v.payload,p_livemode:v.live,p_stripe_checkout_session_id:v.session,p_stripe_customer_id:v.customer,p_subject_id:v.subject,p_tenant_id:v.tenant,p_product_id:v.product,p_billing_interval:v.interval,p_stripe_price_id:v.price});}
export async function recordMarketplaceV12Payment(v:{eventId:string;eventType:string;payload:string;live:boolean;session:string;customer:string;subject:string;tenant:string;product:string;option:string;price:string;revision:string;artifactSha256:string}){if(!/^[a-f0-9]{64}$/.test(v.revision)||!/^[a-f0-9]{64}$/.test(v.artifactSha256))throw new AiMarketplaceCommerceError("Marketplace delivery identity is invalid.",400);return rpc("obserra_ai_marketplace_record_v12_payment",{p_event_id:v.eventId,p_event_type:v.eventType,p_payload_sha256:v.payload,p_livemode:v.live,p_stripe_checkout_session_id:v.session,p_stripe_customer_id:v.customer,p_subject_id:v.subject,p_tenant_id:v.tenant,p_product_id:v.product,p_purchase_option:v.option,p_stripe_price_id:v.price,p_catalog_revision:v.revision,p_artifact_sha256:v.artifactSha256});}
export async function aiMarketplaceLedgerHealth(){const x=await rpc<{operational:boolean;entitlementAuthority:string}>("obserra_ai_marketplace_commerce_health",{});if(!x||x.operational!==true||x.entitlementAuthority!=="ai-marketplace-commerce-ledger-v1")throw new AiMarketplaceCommerceError("Marketplace ledger health is invalid.");return x;}
export async function revokeAiMarketplaceEntitlement(eventId:string,sessionId:string,reason:string){return rpc("obserra_ai_marketplace_revoke_entitlement",{p_event_id:eventId,p_stripe_checkout_session_id:sessionId,p_reason:reason});}
