import "server-only";
import { readFileSync } from "node:fs";
import { gunzipSync } from "node:zlib";
import { join } from "node:path";

export type MarketplaceV12Card = { product_id:string; slug:string; name:string; description:string; mission?:string; family:string; product_type:string; version:string; publication_state:string; proficiency?:string; category?:string; pricing:{currency:string;model:string;pricing_basis?:string;offers:{amount_minor:number;cadence?:string;currency:string;kind:string}[]}; artifact?:{sha256?:string}; visualization:{position_seed:number;scene_cluster:string;relationship_product_ids:string[];object_archetype?:string}; action_policy?:{generated_state?:{action:string;enabled:boolean;label:string;reason_code?:string}}; [key:string]:unknown };
type CatalogDocument={cards:MarketplaceV12Card[];catalog_revision:string;publication_state:string;counts:{total_cards:number}};
type Summary={catalog_revision:string;counts:{total_cards:number;product_cards:number};publication_state:string;family_counts:Record<string,number>;product_type_counts:Record<string,number>};
type CatalogIndex={bySlug:Map<string,MarketplaceV12Card>;byProductId:Map<string,MarketplaceV12Card>;families:Record<string,number>;types:Record<string,number>};
let loaded:{document:CatalogDocument;summary:Summary;index:CatalogIndex}|undefined;
function root(){return join(process.cwd(),"data","marketplace");}
function load(){if(loaded)return loaded;const parsed=JSON.parse(gunzipSync(readFileSync(join(root(),"obserra-marketplace-card-catalog.json.gz"))).toString("utf8")) as Partial<CatalogDocument>;if(!Array.isArray(parsed.cards)||parsed.cards.length!==11396||!parsed.catalog_revision||!parsed.counts)throw new Error("Invalid marketplace v1.2 catalog document");const summary=JSON.parse(readFileSync(join(root(),"obserra-marketplace-card-catalog.summary.json"),"utf8")) as Summary;if(summary.counts.total_cards!==parsed.cards.length||summary.catalog_revision!==parsed.catalog_revision)throw new Error("Marketplace v1.2 catalog summary mismatch");const bySlug=new Map<string,MarketplaceV12Card>(),byProductId=new Map<string,MarketplaceV12Card>();for(const card of parsed.cards){if(!card.slug||!card.product_id||bySlug.has(card.slug)||byProductId.has(card.product_id))throw new Error("Marketplace v1.2 catalog identity collision");bySlug.set(card.slug,card);byProductId.set(card.product_id,card);}loaded={document:parsed as CatalogDocument,summary,index:{bySlug,byProductId,families:summary.family_counts,types:summary.product_type_counts}};return loaded;}
function clean(value?:string|null,max=120){return(value??"").trim().slice(0,max);}
function cursorOffset(cursor?:string){if(!cursor)return 0;if(!/^\d{1,6}$/.test(cursor))return null;const value=Number(cursor);return Number.isSafeInteger(value)&&value>=0?value:null;}
function cardProjection(card:MarketplaceV12Card){const{product_id,slug,name,description,mission,family,product_type,version,publication_state,proficiency,category,pricing,visualization,action_policy}=card;return{product_id,slug,name,description,mission,family,product_type,version,publication_state,proficiency,category,pricing,visualization,action:action_policy?.generated_state??{action:"unavailable",enabled:false,label:"Unavailable",reason_code:"CATALOG_PUBLICATION_REQUIRED"}};}
export function marketplaceV12Summary(){const{document,summary,index}=load();return{revision:document.catalog_revision,publication_state:document.publication_state,total_cards:document.cards.length,family_counts:index.families,product_type_counts:index.types,summary_publication_state:summary.publication_state};}
export function marketplaceV12SalesDock(){const{document,index}=load(),countBy=(value:(card:MarketplaceV12Card)=>string|undefined)=>{const counts=new Map<string,number>();for(const card of document.cards){const key=value(card);if(key)counts.set(key,(counts.get(key)??0)+1);}return[...counts].sort(([a],[b])=>a.localeCompare(b)).map(([id,count])=>({id,count}));};return{families:Object.entries(index.families).sort(([a],[b])=>a.localeCompare(b)).map(([id,count])=>({id,count})),proficiencies:countBy((card)=>card.proficiency),categories:countBy((card)=>card.category).slice(0,24),packages:document.cards.filter((card)=>card.product_type==="collection"||card.product_type==="bundle").map(cardProjection)};}
/** The v1.2 summary defines 11,390 product cards; collections and bundles are catalog containers, not standalone checkout subjects. */
export function marketplaceV12CommerceSubjects(){const{document,summary}=load();const subjects=document.cards.filter((card)=>card.product_type!=="collection"&&card.product_type!=="bundle").map((card)=>({productId:card.product_id,artifactSha256:card.artifact?.sha256??""}));if(subjects.length!==summary.counts.product_cards||subjects.some((subject)=>!/^[a-f0-9]{64}$/.test(subject.artifactSha256)))throw new Error("Marketplace v1.2 commerce-subject integrity mismatch");return subjects;}
export function marketplaceV12Product(identifier:string){const{index}=load();const key=clean(identifier);return index.bySlug.get(key)??index.byProductId.get(key)??null;}
export function marketplaceV12ProductProjection(identifier:string){const card=marketplaceV12Product(identifier);return card?cardProjection(card):null;}
export function marketplaceV12Search(input:{q?:string;family?:string;type?:string;cursor?:string;limit?:number}){const{document,index}=load(),q=clean(input.q).toLocaleLowerCase(),family=clean(input.family),type=clean(input.type),start=cursorOffset(input.cursor),limit=Math.min(60,Math.max(1,Number.isFinite(input.limit)?Math.trunc(input.limit!):24));if(start===null)return{revision:document.catalog_revision,total:0,facets:{families:index.families,product_types:index.types},results:[],nextCursor:null,error:"invalid_cursor" as const};const items=document.cards.filter(card=>(!family||card.family===family)&&(!type||card.product_type===type)&&(!q||`${card.name} ${card.description} ${card.mission??""} ${card.family} ${card.product_type} ${card.proficiency??""} ${card.category??""}`.toLocaleLowerCase().includes(q)));const results=items.slice(start,start+limit).map(cardProjection);return{revision:document.catalog_revision,total:items.length,facets:{families:index.families,product_types:index.types},results,nextCursor:start+results.length<items.length?String(start+results.length):null};}
export function marketplaceV12Facets(){const{document,index}=load();return{revision:document.catalog_revision,total:document.cards.length,families:index.families,product_types:index.types,publication_state:document.publication_state};}
export function marketplaceV12SitemapPage(page:number,pageSize=500){const{document}=load(),safePage=Number.isSafeInteger(page)&&page>=0?page:0,safeSize=Math.min(500,Math.max(1,Math.trunc(pageSize)));return{revision:document.catalog_revision,total:document.cards.length,page:safePage,pageSize:safeSize,entries:document.cards.slice(safePage*safeSize,(safePage+1)*safeSize).map(({slug})=>({slug}))};}
export function marketplaceV12Scene(input:{family?:string;type?:string;q?:string;cursor?:string;limit?:number}){const result=marketplaceV12Search(input),{document}=load(),clusterCounts=new Map<string,number>();for(const card of result.results)clusterCounts.set(card.visualization.scene_cluster,(clusterCounts.get(card.visualization.scene_cluster)??0)+1);return{revision:document.catalog_revision,publication_state:document.publication_state,total:result.total,nextCursor:result.nextCursor,clusters:[...clusterCounts].sort(([a],[b])=>a.localeCompare(b)).map(([id,count])=>({id,count})),nodes:result.results.map(card=>({product_id:card.product_id,slug:card.slug,name:card.name,family:card.family,product_type:card.product_type,position_seed:card.visualization.position_seed,scene_cluster:card.visualization.scene_cluster,relationship_product_ids:card.visualization.relationship_product_ids})),error:"error"in result?result.error:undefined};}
