export const OBSERRIAN_DOCTRINE = {
  title: "The Obserrian Doctrine",
  subtitle: "Executive Stewardship for Institutions Worthy of Trust",
  fullTitle: "The Obserrian Doctrine: Executive Stewardship for Institutions Worthy of Trust",
  author: "Dr. Jody Wayne Blanchard",
  isbn: "9798171759360",
  asin: "B0HHRT2YK7",
  amazonUrl: "https://www.amazon.com/dp/B0HHRT2YK7",
  coverPath: "/books/the-obserrian-doctrine-cover.png",
  coverWidth: 937,
  coverHeight: 1253,
  coverAlt: "Cover of The Obserrian Doctrine: Executive Stewardship for Institutions Worthy of Trust by Dr. Jody Wayne Blanchard",
  hook: "What happens when artificial intelligence can act before leaders fully understand the situation, yet organizations remain accountable for every outcome?",
  overview: [
    "The Obserrian Doctrine gives leaders a human-centered way to use powerful systems in the intelligent age. It is written for executives, security professionals, policymakers, and emerging leaders who must keep human judgment, ethical responsibility, and operational control where they belong: with people.",
    "Dr. Jody Blanchard draws on his experience as a retired U.S. Army intelligence officer, Fortune 500 CISO, and organizational leadership researcher. He connects lessons from military intelligence, global cybersecurity, executive decision-making, and doctoral research, then turns them into a practical doctrine for recognizing risk, making decisions leaders can defend, and building institutions worthy of trust.",
  ],
  readerOutcomes: [
    "Keep human oversight meaningful as automation accelerates",
    "Bring ethical leadership, cybersecurity, compliance, and strategy together",
    "Replace fragmented reporting with a clear, evidence-based view",
    "Spot bias, hidden dependencies, and risks that can cascade across an organization",
    "Lead decisively through ambiguity, disruption, and crisis",
    "Build resilient cultures where accountability stays with people, not technology",
  ],
  digitalTwinDescription: "The book also introduces the Obserra EPI Digital Twin at a leadership level. It is a governed, living representation that helps leaders bring operational, security, risk, and compliance signals together. The discussion stays at the leadership level without revealing proprietary implementation. It shows how trusted dashboards, traceable evidence, and continuous visibility can strengthen oversight and reveal the gap between what an organization believes and what is actually true.",
  futureStatement: "The future will not belong merely to organizations with the most advanced systems. It will belong to leaders who can align intelligence, character, and action.",
  accountabilityStatement: "Technology can recommend. Systems can predict. Leaders remain accountable.",
} as const;
